name=ThingsSentral
version=1.0.0
author=Idlan Zafran Mohd Zaidie
maintainer=Idlan Zafran Mohd Zaidie
sentence=A library to connect ESP8266 and ESP32 devices to the ThingsSentral.io platform.
paragraph=This library provides three core modules: Command for live sending and reading of telemetry data, Vault for offline data persistence using LittleFS, and History for timestamped bulk data payloads.
category=Communication
url=https://github.com/IdlanZafran/ThingsSentral
architectures=esp8266,esp32
depends=ArduinoJson